[tool.commitizen]
version = "0.2.7"
version_files = [
  "package.json:version"
]
bump_message = "chore(release): $current_version â†’ $new_version [skip-ci]"
changelog_incremental = true
changelog_file = "CHANGELOG.md"
changelog_start_rev = "0.2.0"
